### ISSUE TITLE
Chess Plus Plus under Arena 3.5.1 and JRE 8-update 181 and 10.0.2 for x64

### ISSUE THREAD

**Issue by yellow-panther** [louism33/Axolotl#2]
Hello louism33,
[Arena debug.zip](https://github.com/louism33/chessPlusPlus/files/2576430/Arena.debug.zip)

cf. files attached  arena1/2 debug > 5 min match with white/black pieces and JRE 8 update 181; arena3/4 debug - with JRE 10.0.2 (same conditions)

conclusion: engine plays with white pieces: no moves are executed, with the black pieces after 1.Nf3 Nf6 2.d4 respectively 1.e4 e5 2.Nf3 chess plus plus forfeits on time

by the way: JRE 11 is current edition https://www.oracle.com/technetwork/java/javase/downloads/index.html
https://www.oracle.com/technetwork/java/javase/downloads/jre10-downloads-4417026.html

Perhaps you can contact Roman from Russia email: harp07@mail.ru too - his SJCE GUI https://sourceforge.net/projects/sjce/ is created for WB/UCI engines written in Java.

Regards,

**Comment by louism33** [comment]
Hi yellow-panther,

thanks very much for the info. There was a bug in the engine where it was trying to use the whole game time for one move. Now it allots about 5% of the total time to a move. This should fix the problem you kindly noticed. We now support Blitz and fixed time per move. Please let me know if your issue was resolved.

I will definitely consider updating to Java 11, thanks for this information too. Roman's download looks extremely useful, ty very much for this link.

Thanks again for your interest! You are the first person apart from me who has tested my little engine, and I am grateful for your patience :)

Look forward to playing against you soon,

King regards,
Louis
