### ISSUE TITLE
Axolotl v1.2 disappeared

### ISSUE THREAD

**Issue by yellow-panther** [louism33/Axolotl#27]
Hello louism33, what is the reason to come back to v1.1? Was v1.2 buggy?

**Comment by louism33** [comment]
Hi yellow-panther,

Thank you very much for your continued interest in my engine, and I am very sorry for this situation. I have been trying to get more knowledgeable about github / travis / maven, and the development process in general. In doing this, I have made mistakes, including overwriting some code, and causing problems with the previous version of axolotl. 
Because I have also made a very large repository split, I decided to cut my losses, and start again. I did this because I felt that everything had become too confusing. I am really sorry for any confusion this has caused. It is entirely my own fault, but I hope I have learnt enough not to replicate this in future.
I am grateful for your interest, and I hope you can bear with me on this.
The current version of axolotl is 1.1, which is equivalent in strength to the old version.

Thank you very much as always, and please continue to let me know what I can do better in future.

With best regards (und freundlichem Grüßen),

Louis
